spring:
  datasource:
    url: jdbc:mariadb://hanium-videomeeting.ccunwgycpela.ap-northeast-2.rds.amazonaws.com/videoMeeting
    username: hanium0098
    password: qwerty2!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql:
        format_sql: true
logging.level:
  org.hibernate.SQL: debug

openvidu:
  url: https://15.165.67.176:443/
  secret: MY_SECRET

secret: hanium0098
